ansible_user: ansible 
ansible_become: true
ansible_become_method: dzdo 
ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
ansible_python_interpreter: /usr/bin/python3.12 # provide the default python available on Target server
