# The main job for Deployment_Bundle.
resources: 
  jobs:
    PAS_Deployment_Bundle_job:
      name: Deployment_Bundle_job

      tasks:
        - task_key: Sample
          job_cluster_key: job_cluster
          notebook_task:
            notebook_path: ../notebooks/demo.py

      job_clusters:
        - job_cluster_key: job_cluster
          new_cluster:
            spark_version: 14.3.x-scala2.12
            node_type_id: Standard_D8ds_v4
            num_workers: 1
            runtime_engine: PHOTON
            spark_env_vars: {"PYSPARK_PYTHON": "/databricks/python3/bin/python3"}
            azure_attributes:
              first_on_demand : 1
              spot_bid_max_price : 0.4566
