name: Sync Main to Azure DevOps

on:
  push:
    branches:
      - main

  workflow_dispatch: # Allows manual execution    

jobs:
  sync:
    runs-on: [self-hosted, premierinc, linux]

    steps:
      - name: Checkout GitHub repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Push to Azure DevOps
        env:
          AZURE_DEVOPS_PAT: ${{ secrets.AZURE_DEVOPS_PAT }}
        run: |
          # Authenticate with PAT in the repo URL
          ADO_REPO_URL="https://premierinc:${AZURE_DEVOPS_PAT}@dev.azure.com/premierinc/PINC/_git/code-devops-documents"

          git ls-remote "$ADO_REPO_URL"

          # Add or update the remote
          git remote add ado "$ADO_REPO_URL" || git remote set-url ado "$ADO_REPO_URL"
          git fetch ado

          git pull --unshallow || true

          git push ado main --force
